version: "3.8"

services:
  app:
    container_name: app
    image: bitnami/symfony:latest
    volumes:
      - ./app/:/app/
    environment:
      SYMFONY_PROJECT_SKELETON: symfony/skeleton
      SYMFONY_DATABASE_HOST: db
      SYMFONY_DATABASE_NAME: WebJoxTest
      SYMFONY_DATABASE_USER: webjoxtest
      SYMFONY_DATABASE_PASSWORD: webjoxtest
      BITNAMI_DEBUG: true

    ports:
      - "8000:8000"

  ###> doctrine/doctrine-bundle ###
  db:
    container_name: db
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-WebJoxTest}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-webjoxtest}
      POSTGRES_USER: ${POSTGRES_USER:-webjoxtest}
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###


