version: '3.8'

services:
###> symfony/mailer ###
  mailer:
    container_name: mailer
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    labels:
      com.symfony.server.service-prefix: 'MAILER'
###< symfony/mailer ###
